# Auto Mode doesn't create a StorageClass either. This makes encrypted gp3
# volumes the default for PersistentVolumeClaims that don't name a class.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: eks.amazonaws.com/compute-type
        values:
          - auto
parameters:
  type: gp3
  encrypted: "true"
